server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: discoedit_user
    password: discodeit1234

  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
    com.sprint.mission.discodeit: info
